CREATE DATABASE manaserv;

CREATE USER 'manaserv'@'%' IDENTIFIED BY 'manaserv';
GRANT ALTER,CREATE,SELECT,INSERT,UPDATE,DELETE,DROP,INDEX ON `manaserv`.* TO 'manaserv'@'%';

CREATE USER 'manaserv'@'127.0.0.1' IDENTIFIED BY 'manaserv';
GRANT ALTER,CREATE,SELECT,INSERT,UPDATE,DELETE,DROP,INDEX ON `manaserv`.* TO 'manaserv'@'127.0.0.1';

FLUSH PRIVILEGES;
